### ISSUE TITLE
Invalid config: Key 'file' while using pyproject.toml

### ISSUE THREAD

**Issue by elgalu** [dmerejkowsky/tbump#104]
I was trying to use `pyproject.toml` as according to the docs:

```toml
[[tool.tbump.file]]
src = "pyproject.toml"
search = 'version = "{current_version}"'
```

However I kept getting this error:

```py
Error: Invalid config: Key 'file' error:
Or(Schema({'src': <class 'str'>, Optional('search'): <class 'str'>, Optional('version_template'): <class 'str'>})) did not validate {'src': 'pyproject.toml', 'search': 'version = "{current_version}"'}
Schema({'src': <class 'str'>, Optional('search'): <class 'str'>, Optional('version_template'): <class 'str'>}).validate({'src': 'pyproject.toml', 'search': 'version = "{current_version}"'}) raised TypeError("__init__() missing 3 required positional arguments: 'value', 'trivia', and 'is_aot_element'")
```

Got fixed as soon as I re-wrote the conf into `tbump.toml`

Python 3.9.5 , venv, tbump from master branch, latest poetry, also using poetry-version-plugin

**Comment by dmerejkowsky** [comment]
I think that's the same bug as #103

I think you are getting this error because:

* The `master` branch has been renamed to `main`
* No tbump release was made with the aforementionned fiixed

Also, beware of #93, which I did not have time to fix yet :(
