### ISSUE TITLE
6.4 Release?

### ISSUE THREAD

**Issue by afshin** [dmerejkowsky/tbump#114]
Hi @dmerejkowsky!  Thank you so much for `tbump`!

Had you meant to publish a 6.4.0 to PyPi on [2021-06-22](https://github.com/dmerejkowsky/tbump/blob/main/Changelog.rst#640-2021-06-22)?

We have had to pin `tomlkit` pending a release with #105.

**Comment by dmerejkowsky** [comment]
> Had you meant to publish a 6.4.0 to PyPi on 2021-06-22?

Looks like it :stuck_out_tongue:  - must have been busy with other stuff.

**Comment by dmerejkowsky** [comment]
Done - thanks for letting me know and sorry for the delay.

**Comment by blink1073** [comment]
Thank you!

**Comment by afshin** [comment]
Thank you!
