### ISSUE TITLE
Push the commits and the tag simoultaneously

### ISSUE THREAD

**Issue by InCogNiTo124** [dmerejkowsky/tbump#117]
Instead of pushing twice, which spawns two workflows, how about using something along the lines of

`git push --atomic origin <branch name> <tag>`

What are your thoughts on that?

**Comment by InCogNiTo124** [comment]
> Looks like a good idea. Do you want to try and write a patch for this ?

Sure. I'll try to do this week :))

**Comment by mihaiginta** [comment]
Is there a way to deactivate the `--atomic` flag? My remote does not support it

**Comment by dmerejkowsky** [comment]
> A workaround would be to push the tag separately, I guess?

Indeed. Something like `tbump 1.2.3 --no-tag-push ; git push origin v1.2.3`
