### ISSUE TITLE
Feature: bumping patch, minor and major versions more easily

### ISSUE THREAD

**Issue by InCogNiTo124** [dmerejkowsky/tbump#134]
At the moment, `tbump` works by providing the version to upgrade to.

however, this implies knowledge about the current version of the developed software. Sometimes after many weeks of not working on a particular project I honestly forget with which version I tagged it last time. 😅 

Sure, I can look it up in `pyproject.toml` or `git log`, but I suggest the following new flags:
- `tbump --patch` to bump the patch version (eg from v0.0.2 to v0.0.3)
- `tbump --minor` to bump the minor version (eg from v0.0.3 to v0.1.0)
- `tbump --major` to bump the major version (eg from v0.1.0 to v1.0.0)

**Comment by dmerejkowsky** [comment]
Sorry, there's already been a discussion about this. See #73, #107

**Comment by InCogNiTo124** [comment]
Oh, okay. Sorry for not searching beforehand :sweat_smile: 

Does that mean that, even if someone were to implement that functionality and contribute, you still wouldn't merge it?

**Comment by dmerejkowsky** [comment]
> Does that mean that, even if someone were to implement that functionality and contribute, you still wouldn't merge it?

Yup. That would be a disservice to future maintainers - which could include that very same benevolent contributor :)
